locale: "es-ES"
title: "José Zapatero"
title_separator: "-"
name: "José Zapatero"
description: "Brewing and FMCG Professional"
url: "https://josezapatero.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

markdown: kramdown
paginate: 5
paginate_path: /page:num/

author:
  name: "José Zapatero"
  bio: "Packaging & Manufacturing Excellence Manager"
  location: "Cuba"
  links:
    - label: "Correo"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:jmazsantos@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/tu-usuario"

footer:
  links:
    - label: "Correo"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:jmazsantos@gmail.com"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
